BattleArena v3.9.9.15
- Adds new config.yml option for rake:

defaultOptions.defaultDuelOptions: [rake=5.0]

This means rake = 5%

Which means that if the pot is $200 then the winner will receieve 95% (or
$190).

- This is also the long awaited fix for ArenaSpleef.

1. http://hastebin.com/logukaweyo.tex
2. http://hastebin.com/qozacodomi.tex

These were the errors produced by ArenaSpleef. The actual 'fix' is
contained in WorldEditUtil v1.1.2:

1. The first error was a NullPointerException
at
mc.alk.arena.plugins.worldguard.WorldGuardAbstraction.createRegion(WorldGuardAbstraction.java:105)

Which was invoking two different objects on the same line:
wgp.getGlobalRegionManager().get(w);

It turns out that wgp field was null (surprising and almost not surprising
at
the same time).

Previously, this field was being set thru a setter() method
setWorldGuard().
The simple solution was to assign it on object creation (at the point of
declaration). However, this might be changed in the future to where the
object is passed via the constructor (dependency injection - a better
solution).

2. The second error was a NoSuchMethodError

Caused by: java.lang.NoSuchMethodError:
com.sk89q.worldguard.protection.managers.RegionManager.removeRegion(Ljava/lang/String;)V

It turns out that the return type in WG v5 is void
and the return type in WG v6 is a Set<ProtectedRegion>

This was super easy to fix:
I simply abstracted out the deleteRegion() method

Now v5 & v6 have their own implementation...
each one calling WorldGuard's own .removeRegion() method.