Update util.MapOfTreeSet
https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html#remove-java.lang.Object-java.lang.Object-

HashMap.remove(object, object) was added in jdk8, which would cause this
compilation error:

error: name clash: remove(K,V) in MapOfTreeSet and remove(Object,Object)
in HashMap have the same erasure, yet neither overrides the other

MapOfTreeSet.remove() was renamed since the intention is different from
HashMap.remove()

renamed: MapOfTreeSet.remove(K k, V v) -> removeValue(K k, V v);

// Uses key (k) to get the Set, then removes the value (v) from the Set.